spring.application.name=ShippingPlanner


# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ShippingPlannerDB
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configuration du serveur
server.port=8080

# Configuration du logging
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Autres configurations
spring.main.allow-circular-references=true
spring.security.enabled=false

demo.app.jwtSecret=qJ8r9K1f3Q2eH6mJ0vY4PzB7cL8nR5tU0xW2yZ3a=
demo.app.jwtExpirationMs=86400000   # 24h en ms

